#!/bin/bash
#
# pulseaudio-ctl
#
# simple control of pulseaudio vol+/vol-/mute from the shell
# or more practically, from DE shortcut keys
#
# by graysky
# https://github.com/graysky2/pulseaudio-ctl

export BLD="\e[01m" BLU="\e[01;34m" RED="\e[01;31m" NRM="\e[00m"
command -v sed >/dev/null 2>&1 || {
echo "I require sed but it's not installed. Aborting." >&2
exit 1; }

command -v awk >/dev/null 2>&1 || {
echo "I require awk but it's not installed. Aborting." >&2
exit 1; }

command -v pactl >/dev/null 2>&1 || {
echo "I require pactl but it's not installed. Aborting." >&2
exit 1; }

command -v pacmd >/dev/null 2>&1 || {
echo "I require pactl but it's not installed. Aborting." >&2
exit 1; }

setup() {
	#SINK=$(pactl info|grep "Default Sink"|awk '{print $3}')
	SINK=$(pacmd list-sinks|awk '/* index:/{ print $3 }')
	MUTED=$(pacmd list-sinks|grep -A 15 '* index'|awk '/muted:/{ print $2 }')
	CURVOL=$(pacmd list-sinks|grep -A 15 '* index'| awk '/volume: 0:/{ print $3 }'|sed 's/%//')

	if [[ "$CURVOL" =~ ^[0-9]+$ ]]; then
		return 0
	else
		# the git snapshot at the time of writing this script chances the
		# expected output of this cmd
		CURVOL=$(pacmd list-sinks|grep -A 15 '* index'| awk '/volume:/{ print $5 }' | sed 's/%//g')
	fi
}

case "$1" in
	U|u|[U,u]p)
		# raise volume by 5%
		setup
		[[ $CURVOL -ge 100 ]] && exit 0 ||
		pactl set-sink-volume "$SINK" -- +5%
		;;
	D|d|[D,d]own|[D,d]o)
		# lowers volume by 5%
		setup
		[[ $CURVOL -le 0 ]] && exit 0 ||
		pactl set-sink-volume "$SINK" -- -5%
		;;
	M|m|[M,m]u|[M,m]ute)
		# mutes the volume entirely
		setup
		pactl set-sink-mute "$SINK" toggle
		;;
	*)
		setup
		echo -e " ${BLD}$0 ${NRM}${BLU}{up,down,mute}${NRM}"
		echo
		echo -e " ${BLD}Where ${NRM}${BLU}up${NRM}${BLD} and ${NRM}${BLU}down${NRM}${BLD} adjust volume in ±5 % increments.${NRM}"
		echo -e " ${BLD}Where ${NRM}${BLU}mute${NRM}${BLD} toggles the mute status on/off.${NRM}"
		echo
		echo -e " ${BLD}Volume level  : ${NRM}${RED}$CURVOL %${NRM}"
		echo -e " ${BLD}Is sink muted : ${NRM}${RED}$MUTED${NRM}"
		exit 0
		;;
esac
