#!/bin/bash
# Inspiration to Roland Latour who wrote most of this script
# http://www.freak-search.com/en/thread/4707111/q_volume_control,_xfce

command -v sed >/dev/null 2>&1 || {
echo "I require sed but it's not installed. Aborting." >&2
exit 1; }

command -v awk >/dev/null 2>&1 || {
echo "I require awk but it's not installed. Aborting." >&2
exit 1; }

command -v pactl >/dev/null 2>&1 || {
echo "I require pactl but it's not installed. Aborting." >&2
exit 1; }

command -v pacmd >/dev/null 2>&1 || {
echo "I require pactl but it's not installed. Aborting." >&2
exit 1; }

export BLD="\e[01m" BLU="\e[01;34m" NRM="\e[00m"

#find default sink
sink=$(pacmd info|grep "Default sink name"|awk '{print $4}')

# find volume of default sink
# get line# of start of definition for default sink (plus 1, actually)
let line=$(pacmd list-sinks|grep -n $sink|sed '{s/://}'|awk '{print $1}')

case "$1" in
	U|u|[U,u]p)
		# raise volume by 5%
		# index down a bit for volume line
		let line=($line + 6)

		volume=$(pacmd list-sinks|awk 'NR=="'"$line"'"{print $3}'|sed '{s/%//}')

		[[ $volume -gt 100 ]] && volume=100 && exit 0
		pactl set-sink-volume "$sink" -- +5%
		;;
	D|d|[D,d]own|[D,d]o)
		# lowers volume by 5%
		# index down a bit for volume line
		let line=($line + 6)

		volume=$(pacmd list-sinks|awk 'NR=="'"$line"'"{print $3}'|sed '{s/%//}')

		[[ $volume -lt 0 ]] && volume=0 && exit 0
		pactl set-sink-volume "$sink" -- -5%
		;;
	M|m|[M,m]u|[M,m]ute)
		# mutes the volume entirely
		# add 12 for "muted" line
		let line=($line + 12)

		mute=$(pacmd list-sinks|awk 'NR==i"'"$line"'"{print $2}')

		# backwards-compatibility fix by WOFall
		[[ "$mute" == "request:" ]] && pactl set-sink-mute "$sink" toggle > /dev/null 2>&1

		[[ "$mute" == "yes" ]] && pactl set-sink-mute "$sink" 0 > /dev/null 2>&1
		[[ "$mute" == "no" ]] && pactl set-sink-mute "$sink" 1 > /dev/null 2>&1
		;;
	*)
		echo -e " ${BLD}$0 ${NRM}${BLU}{up,down,mute}${NRM}"
		echo
		echo -e " ${BLD}Where ${NRM}${BLU}up${NRM}${BLD} and ${NRM}${BLU}down${NRM}${BLD} adjust volume in ±5 % increments.${NRM}"
		echo -e " ${BLD}Where ${NRM}${BLU}mute${NRM}${BLD} toggles the mute status on/off.${NRM}"
		exit 0
		;;
esac
